# from .nodes import GENERAL_NODE_CLASS_MAPPINGS, GENERAL_NODE_DISPLAY_NAME_MAPPINGS
from .web import WEB_NODE_CLASS_MAPPINGS, WEB_NODE_DISPLAY_NAME_MAPPINGS

# NODE_CLASS_MAPPINGS = GENERAL_NODE_CLASS_MAPPINGS.update(COMPONENT_NODE_CLASS_MAPPINGS)
# NODE_DISPLAY_NAME_MAPPINGS = GENERAL_NODE_DISPLAY_NAME_MAPPINGS.update(COMPONENT_NODE_DISPLAY_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS = {}
# NODE_CLASS_MAPPINGS.update(GENERAL_NODE_CLASS_MAPPINGS)
NODE_CLASS_MAPPINGS.update(WEB_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
# NODE_DISPLAY_NAME_MAPPINGS.update(GENERAL_NODE_DISPLAY_NAME_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(WEB_NODE_DISPLAY_NAME_MAPPINGS)


